# Generated by Django 4.1.3 on 2022-11-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lancamento', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('direcao', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('empresa_produtora_br_majoritaria', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=100)),
                ('renda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalasUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('qtd_salas', models.IntegerField()),
                ('ano_atualizacao', models.IntegerField()),
            ],
        ),
    ]
